services:
  bot:
    build: .
    image: love-bot:latest
    container_name: love-bot
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    depends_on:
      - duckling

  duckling:
    image: rasa/duckling:0.2.0.2-r3
    container_name: duckling
    ports:
      - "8000:8000"
    restart: unless-stopped
